export const PASSWORD_RESET_SUCCESS = 'ResetPassword/PASSWORD_RESET_SUCCESS';
export const CHECK_TOKEN_VERIFICATION = 'ResetPassword/CHECK_TOKEN_VERIFICATION';
export const TOKEN_CHECK_FAILURE = 'ResetPassword/TOKEN_CHECK_FAILURE';
export const RESET_RESET_PASSWORD_PARAMS = 'ResetPassword/RESET_FORGOT_PASSWORD_PARAMS';