export const RESET_DASHBOARD = 'Home/RESET_DASHBOARD';
export const LOAD_PROPERTIES = 'Home/LOAD_PROPERTIES';
export const LOAD_PROPERTIES_ERROR = 'Home/LOAD_PROPERTIES_ERROR';
export const UPDATE_FILTER = 'Home/UPDATE_FILTER';
export const UPDATE_PAGE_NUMBER = 'Home/UPDATE_PAGE_NUMBER';
export const DOWNLOAD_SDK = 'Home/DOWNLOAD_SDK'